# Generated by Django 3.1.1 on 2020-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('massage_id', models.AutoField(primary_key=True, serialize=False)),
                ('nmae', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('massage', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_author',
        ),
    ]
