# Generated by Django 3.1.1 on 2020-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200911_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
