# Generated by Django 3.1.1 on 2020-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200915_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='designation',
        ),
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
