# Generated by Django 3.1.1 on 2020-09-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_author_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='status',
        ),
    ]
