# Generated by Django 3.1.1 on 2020-11-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200926_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='cover_picture',
            field=models.ImageField(blank=True, default='cover_image.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='author',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='author',
            name='designation',
        ),
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.ManyToManyField(to='posts.Designation'),
        ),
    ]
