# Generated by Django 3.1.1 on 2020-12-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='designation',
        ),
        migrations.AddField(
            model_name='author',
            name='user_check',
            field=models.BooleanField(default=False),
        ),
    ]
