# Generated by Django 3.1.1 on 2020-12-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201208_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation', to='posts.designation'),
        ),
    ]
