# Generated by Django 3.1.1 on 2020-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_author_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='professionals_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='student_check',
            field=models.BooleanField(default=False),
        ),
    ]
